sudo: required
services:
  - docker
  
 before_install:
   - docker build -t angurana/docker-react -f Dockerfile.dev .
   
 script:
   - docker run angurana/docker-react npm run test -- --coverage
   
 deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker_react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-306476627547"
    bucker_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "AWS_SECRET_KEY"
      
   